application:
  version: @project.version@

retriever:
  url: https://marketdata.set.or.th/mkt/sectorialindices.do?language=en&country=US
  schedule:
    period: 5s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create-drop #update #create-drop if want to create new table